#!/bin/sh
eval "$*"
. CONFDIR/gen-initramfs.conf || exit 1

if test -z "$kver"; then
       	kver="$(uname -r)"
fi

if test -z "$prefix"; then
	prefix=/usr
fi

if test -z "$sysroot"; then
       	sysroot=/
fi

if test -n "$bin"; then
	bin="$(echo $bin | sed 's/,/ /g')"
fi

if test -n "$lib"; then
	lib="$(echo $lib | sed 's/,/ /g')"
fi

if test -n "$hooks"; then
       	hooks="$(echo $hooks | sed 's/,/ /g')"
fi

if test -n "$drivers"; then
	drivers="$(echo $drivers | sed 's/,/ /g')"
fi

work="$(pwd)/workdir"

test -d $work && echo "$work exists! Remove or move it for the process" && exit 1
mkdir -p $work
cd $work 

echo "(1/3) Working on essential files..."
cp -r $sysroot/usr/share/gen-initramfs/busybox-initramfs/* .
mkdir -p new_root hooks-before hooks-after \
	etc usr/lib usr/bin var tmp run sys proc \
	dev lib64 mnt opt root var

ln -sf usr/bin bin 
ln -sf usr/bin sbin
ln -sf usr/bin usr/sbin

ln -sf usr/lib lib
ln -sf usr/lib lib64
ln -sf usr/lib usr/lib64

mknod -m 640 dev/console c 5 1
mknod -m 664 dev/null    c 1 3


liblink=$(readlink $sysroot/lib) 
if test -z "$liblink"; then 
	liblink=/lib
fi

for x in $bin; do
	cp -r $sysroot/$bindir/$x $workdir/$bindir/$x
done

for x in $lib; do
 cp $sysroot/$libdir/$x $work/$libdir/$x
done

for x in $hooks; do 
	for y in "before" "between" "after"; do 
		filetype=".$y"
		stage="-$y"

		if test -f "$sysroot/$prefix/share/gen-initramfs/hooks/${x}${y}"; then
		       	install -Dm755 $sysroot/$prefix/share/gen-initramfs/hooks/"${x}${y}" ./hooks$stage/$x
			eval hooks_${y}=\"\$hooks_${y} $x\"
		fi
	done
	
	if test -f $sysroot/$prefix/share/gen-initramfs/hooks/$x.sh; then
		. $sysroot/$prefix/share/gen-initramfs/hooks/$x.sh
	fi
	eval "echo hooks_${y}=\"\$hooks_${y}\" >> $work/hookorder"
done

echo "(2/3) Copying init file..."
install -Dm755 $sysroot/$prefix/share/gen-initramfs/init.in ./init

echo "(3/3) Generating initramfs..."
find . | cpio -o -H newc | gzip -9 > initramfs-$kver.img

addmod() {
for modpath in $*; do 
	cp -r $sysroot/$liblink/modules/$kver/kernel/$modpath \
		$workdir/$liblink/modules/$kver/kernel/$(dirname $modpath)
done
}
