#!/bin/sh
eval "$*"
. //etc/gen-initramfs.conf || exit 1

if test -z "$kver"; then
       	kver="$(uname -r)"
fi

if test -z "$prefix"; then
	prefix=/usr
fi

if test -z "$sysroot"; then
       	sysroot=/
fi

if test -n "$bin"; then
	bin="$(echo $bin | sed 's/,/ /g')"
fi

if test -n "$lib"; then
	lib="$(echo $lib | sed 's/,/ /g')"
fi

if test -n "$hooks"; then
       	hooks="$(echo $hooks | sed 's/,/ /g')"
fi

if test -n "$drivers"; then
	drivers="$(echo $drivers | sed 's/,/ /g')"
fi

work="$(pwd)/workdir"
dirmod="modules/$kver/kernel"
hookdir="share/gen-initramfs/hooks/"
workdir="$work"

test -d $work && echo "$work exists! Remove or move it for the process" && exit 1
mkdir -p $work
cd $work 

echo "(1/3) Working on essential files..."
cp -r $sysroot/usr/share/gen-initramfs/busybox-initramfs/* .
mkdir -p new_root hooks-before hook-between hooks-after \
	etc usr/lib usr/bin var tmp run sys proc \
	dev lib64 mnt opt root var

ln -sf usr/bin bin 
ln -sf usr/bin sbin
ln -sf usr/bin usr/sbin

ln -sf usr/lib lib
ln -sf usr/lib lib64
ln -sf usr/lib usr/lib64

mknod -m 640 dev/console c 5 1
mknod -m 664 dev/null    c 1 3


liblink=$(readlink $sysroot/lib) 
if test -z "$liblink"; then 
	liblink=/lib
fi

for x in $hooks; do 
	test -f $sysroot/$prefix/$hookdir/$x.before && \
		install -Dm755 $sysroot/$prefix/$hookdir/$x.before $workdir/hooks-before && \
		hooks_before="$hooks_before $x"
	test -f $sysroot/$prefix/$hookdir/$x.between && \
		install -Dm755 $sysroot/$prefix/$hookdir/$x.between $workdir/hooks-between && \
		hooks_between="$hooks_between $x"
	test -f $sysroot/$prefix/$hookdir/$x.after && \
		install -Dm755 $sysroot/$prefix/$hookdir/$x.after $workdir/hooks-after && \
		hooks_after="$hooks_after $x"
	
	if test -f $sysroot/$prefix/share/gen-initramfs/hooks/$x.sh; then
		echo "::Adding prerequisite for $x"
		. $sysroot/$prefix/share/gen-initramfs/hooks/$x.sh
	fi
	echo $hook_before 
	echo $hook_between
	echo $hook_after
done

echo "(2/3) Copying init file..."
install -Dm755 $sysroot/$prefix/share/gen-initramfs/init.in ./init

echo "(3/3) Generating initramfs..."
find . | cpio -o -H newc | gzip -9 > initramfs-$kver.img
