addmod drivers/net/wireless
addmod drivers/mmc/core/mmc_core.ko*
addmod net/mac80211/mac80211.ko*
addmod net/rekill/rfkill.ko*
addmod drivers/soc/qcom/qmi_helpers.ko*
addmod drivers/hwmon/hwmon.ko*
addmod drivers/bcma/bcma.ko* 
addmod drivers/ssb/ssb.ko*
addmod drivers/char/hw_random/rng-core.ko* 
addmod lib/math/cordic.ko*
addmod drivers/virtio/virtio.ko*
addmod drivers/virtio/virtio_ring.ko*
addmod lib/crc-ccitt.ko*
addmod drivers/net/mii.ko*
addmod drivers/net/usb/usbnet.ko*
addmod drivers/net/usb/rndis_host.ko*
addmod drivers/misc/eeprom/eeprom_93cx6.ko*
addmod lib/crc-itu-t.ko* 
